//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalFolders.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrystalFolders.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app is already in its initial state!.
        /// </summary>
        public static string AppAlreadyInitialState {
            get {
                return ResourceManager.GetString("AppAlreadyInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Customization.
        /// </summary>
        public static string ApplyCustomization {
            get {
                return ResourceManager.GetString("ApplyCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App has been refreshed to default state..
        /// </summary>
        public static string AppRefreshed {
            get {
                return ResourceManager.GetString("AppRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an icon first!.
        /// </summary>
        public static string ChooseAnIconFirst {
            get {
                return ResourceManager.GetString("ChooseAnIconFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Folders.
        /// </summary>
        public static string CrystalFoldersTitle {
            get {
                return ResourceManager.GetString("CrystalFoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Icons.
        /// </summary>
        public static string CrystalIconsTitle {
            get {
                return ResourceManager.GetString("CrystalIconsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening link:.
        /// </summary>
        public static string ErrorOpeningLink {
            get {
                return ResourceManager.GetString("ErrorOpeningLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders restored successfully..
        /// </summary>
        public static string FoldersHaveBeenRestored {
            get {
                return ResourceManager.GetString("FoldersHaveBeenRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders list cleared..
        /// </summary>
        public static string FoldersListCleared {
            get {
                return ResourceManager.GetString("FoldersListCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global font collection for writing in all modern and ancient languages.
        /// </summary>
        public static string GlobalFontCollectionDesc {
            get {
                return ResourceManager.GetString("GlobalFontCollectionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Files.
        /// </summary>
        public static string IconFiles {
            get {
                return ResourceManager.GetString("IconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons applied!.
        /// </summary>
        public static string IconsApplied {
            get {
                return ResourceManager.GetString("IconsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid icon file.
        /// </summary>
        public static string InvalidIconFile {
            get {
                return ResourceManager.GetString("InvalidIconFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string LanguageArabic {
            get {
                return ResourceManager.GetString("LanguageArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List is empty!.
        /// </summary>
        public static string ListAlreadyEmpty {
            get {
                return ResourceManager.GetString("ListAlreadyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Mode.
        /// </summary>
        public static string NormalMode {
            get {
                return ResourceManager.GetString("NormalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select items!.
        /// </summary>
        public static string PleaseSelectItems {
            get {
                return ResourceManager.GetString("PleaseSelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore mode active..
        /// </summary>
        public static string RestoreModeActive {
            get {
                return ResourceManager.GetString("RestoreModeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore To Default.
        /// </summary>
        public static string RestoreToDefault {
            get {
                return ResourceManager.GetString("RestoreToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folders.
        /// </summary>
        public static string SelectFolders {
            get {
                return ResourceManager.GetString("SelectFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your folders are being customized..
        /// </summary>
        public static string YourFoldersAreBeingCustomized {
            get {
                return ResourceManager.GetString("YourFoldersAreBeingCustomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your folders are being restored..
        /// </summary>
        public static string YourFoldersAreBeingRestored {
            get {
                return ResourceManager.GetString("YourFoldersAreBeingRestored", resourceCulture);
            }
        }
    }
}
